#!/bin/bash

## Define all variable
BANNER="X19fX19fIF8gICAgICAgICAgICAgICAgICAgICAgICAgICAgIF8gICBfICAgICAgXyAgICAgICAgICAgICAgICAgCnwgX19fIFwgfCAgICAgICAgICAgICAgICAgICAgICAgICAgIHwgfCB8IHwgICAgfCB8ICAgICAgICAgICAgICAgIAp8IHxfLyAvIHwgX18gXyBfX18gXyBfXyBfX18gICBfXyBfICB8IHxffCB8IF9fX3wgfF8gX18gICBfX18gXyBfXyAKfCAgX18vfCB8LyBfYCAvIF9ffCAnXyBgIF8gXCAvIF9gIHwgfCAgXyAgfC8gXyBcIHwgJ18gXCAvIF8gXCAnX198CnwgfCAgIHwgfCAoX3wgXF9fIFwgfCB8IHwgfCB8IChffCB8IHwgfCB8IHwgIF9fLyB8IHxfKSB8ICBfXy8gfCAgIApcX3wgICB8X3xcX18sX3xfX18vX3wgfF98IHxffFxfXyxffCBcX3wgfF8vXF9fX3xffCAuX18vIFxfX198X3wgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHwgfCAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8X3wgWyB2ZXJzaW9uIF0K"
TEMPLATE="H4sIAO/4tVsAA0WP3UrDQBCFrztPMbRCYwrGaxNFxCKCeOedsGx2J81iOgn7A5GSd3eT2i0MO8N39hxmihxyfJbBt73F07lPkBcAG8OqC5qwqo13hfNa7XZ37RMEZ/iALI/kBqkIo1LG75oaw4Sv+5evN/Q2UEI32XiLJ9NgtohxVn3wWFUoxMf7516IeV4/4HruY4kXmVh35TSlILEEXdTNuNjw8d93dVy3GWocgmtFLdVPgo2JZZ1PwM2letaJzDm4/eYtgP8dKFLs+nj1+enivYY9HqXhLG4EK4CVJR8s430J0x/K6pV+VQEAAA=="
VERSION="v1.1"
MAX=`ls | grep plasma-in | wc -l`
CASE=1
CASE_PASSED=()
CASE_FAILED=()

## Define all func
resize() {
	printf '\033[8;40;100t'
}

banner() {
	echo ${BANNER} | base64 -d | sed "s/version/${VERSION}/g"
}

usage() {
	banner
	# how to use plasma-helper
}

compile() {
	echo -en "[!] Compiling the program... [??]\r"
	g++ -std=c++11 ${1} -o ${1//.cpp}

	[[ ! $? -eq 0 ]] && {
		echo "ERROR: Failed to compile the program"
		exit 1
	}
	
	echo -en "[*] Compiling the program... [OK]\n"
}

loader() {
	let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*4)/10
    let _left=40-$_done
	
	_fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

	printf "\r[${_fill// /\#}${_empty// /-}] ${3} - ${_progress}%%"
}

testcase() {
	result=`cat ${1} | ./${3}`
	_c=${2//.txt}

	sleep 1
	if [[ ${result} = `cat plasma-out-${2}` ]]; then
		CASE_PASSED+=(${_c})
		loader ${_c} ${4} "${1} [PASSED]"
	else 
		CASE_FAILED+=(${_c})
		loader ${_c} ${4} "${1} [FAILED]"
	fi

	(( CASE++ ))
}

## Main
[[ $# -eq 0 ]] && {
	resize
	echo "[!] Usage: plasma-helper [-c create file from template] [-d check testcase result] || [-h help]"
	exit 1
}

while [ "$1" != "" ]; do
    argv=`echo $1 | awk -F= '{print $1}'`
    val=`echo $2 | sed 's/^[^=]*=//g'`
    case $argv in
        -h | --help)
			usage && exit 1
            ;;
        -i | --init)
			banner
			echo "[+] Create sample input"
			read -p ">> press <enter> to continue"

			# add new file for input
			c=1
			for i in `ls | grep plasma-in`; do
				(( c++ ))
			done;
			nano plasma-in-${c}.txt
			
			# add new file for output
			echo "[+] Create sample output"
			read -p ">> press <enter> to continue"
			nano plasma-out-${c}.txt
			;;
        -c | --create)
			echo ${TEMPLATE} | base64 -d | gunzip | sed "s/{author}/$(whoami)/g" >> ${val}
            ;;
        -d | --deploy)
			[[ ! `echo ${val} | cut -d'.' -f2` = cpp ]] && {
				echo "ERROR: The extension must be .cpp"
				exit 1
			}

			compile ${val}

			[[ ! -f plasma-in-1.txt ]] && {
				echo "[!] File testcase not exist !!"
				exit 1
			}

			echo "" # endl
			for i in `ls | grep plasma-in`; do
				out=`echo ${i} | cut -d'-' -f3`
				testcase ${i} ${out} ${val//.cpp} ${MAX}
			done;
			echo "" && echo "" # endl
			
			echo "[INFO] ${MAX} tests, ${#CASE_PASSED[@]} passed, ${#CASE_FAILED[@]} failed"
			
			[[ ${#CASE_FAILED[@]} -ge 0 ]] && {
				for i in ${CASE_FAILED[@]}; do
					echo "[ERROR] CASE#${i} output should be" `cat plasma-out-${i}.txt`
				done;
			}

			rm ${val//.cpp}
            ;;
        *)
            exit 1
            ;;
    esac
    shift
done;