#!/bin/bash

[[ $# -ne 1 ]] && {
	echo "[!] Usage: plasma-helper example.cpp"
	exit 1
}

[[ ! `echo ${1} | cut -d'.' -f2` = cpp ]] && {
	echo "[x] The extension must be .cpp"
	exit 1
}

g++ -std=c++11 ${1} -o ${1//.cpp}

[[ ! $? -eq 0 ]] && {
	echo "[x] Failed to compile the program"
	exit 1
}

n=1
for case in `ls | grep txt`; do
	result=`cat ${case} | head -n $(cat ${case} | wc -l) | ./${1//.cpp}`

	if [[ ${result} = `cat ${case} | tail -n 1` ]]; then
		echo ">> CASE #${n} [PASSED]"
	else
		echo ">> CASE #${n} [FAILED]"
	fi

	(( n++ ))
done;